sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t abhisheksinha4795/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true abhisheksinha4795/docker-react npm run test -- --coverage